USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_SUPPLY_CHAIN;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM RAW.CUSTOMER_STREAM
ON TABLE RAW.CUSTOMERS;

CREATE OR REPLACE STREAM RAW.PRODUCT_STREAM
ON TABLE RAW.PRODUCTS;

CREATE OR REPLACE STREAM RAW.SALES_STREAM
ON TABLE RAW.SALES;