USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_SUPPLY_CHAIN;

SELECT
    'CUSTOMERS' AS entity,
    COUNT(*) AS BATCH_01_count
FROM RAW.CUSTOMERS
WHERE _batch_id = 'BATCH_01'

UNION ALL

SELECT
    'PRODUCTS',
    COUNT(*)
FROM RAW.PRODUCTS
WHERE _batch_id = 'BATCH_01'

UNION ALL

SELECT
    'SALES',
    COUNT(*)
FROM RAW.SALES
WHERE _batch_id = 'BATCH_01';